### ISSUE TITLE
Breaks ARCCW "Replace TTT Weapons"

### ISSUE THREAD

**Issue by DOTD100** [wgetJane/ttt-weapon-rework#1]
Like title said. The only thing that will spawn from ARCCW would be the grenades and very rarely an ARCCW gun.

Guessing this have something to do with the weapons being spawned instantly?

**Comment by wgetJane** [comment]
this addon isn't really supposed to be used with other addons that add spawnable guns

this is the file that handles weapon spawning: https://github.com/wgetJane/ttt-weapon-rework/blob/master/lua/tttwr/sv_replace.lua

**Comment by DOTD100** [comment]
Ah, that explains it. Kinda my bad in expecting other weapons to work-
